### ISSUE TITLE
Rotating circuit tile entity causes game crash

### ISSUE THREAD

**Issue by Random-Scientist** [Da-Technomancer/Essentials#100]
reported in https://github.com/Crossroads-Development/Crossroads/issues/295

**Comment by Random-Scientist** [comment]
> ```
> [18:33:15] [Server thread/INFO]: Redirecting com/Da_Technomancer/essentials/blocks/redstone/CircuitTileEntity$Orient
> [18:33:15] [Server thread/ERROR]: Encountered an unexpected exception
> net.minecraft.ReportedException: Exception ticking world
> 	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[client-1.20.1-20230612.114412-srg.jar%23588!/:?]
> 	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23588!/:?]
> 	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23588!/:?]
> 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23588!/:?]
> 	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23588!/:?]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Direction.m_122429_()" because "p_121946_" is null
> ```
> (this section from the log seems to be the root of the issue)

**Comment by Random-Scientist** [comment]
Closing this as stale, original reporter (@NHblock714) didn't respond to questions over on the CR issue tracker (hi, if you are reading this and can still reproduce this silly bug please reopen with more info :))
