### ISSUE TITLE
Crash after name change.

### ISSUE THREAD

**Issue by Buttersxx** [Da-Technomancer/Essentials#101]
changed the name of my Minecraft instance to. Now it crashes on start up and i get this log.

Time: 2024-10-10 15:19:35
Description: Initializing game

java.io.FileNotFoundException: \curseforge\minecraft\Instances\hALLOWEEN_\essential\Essential (forge_1.20.1).jar (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method) ~[?:?] {re:mixin}
	at java.io.FileInputStream.open(FileInputStream.java:216) ~[?:?] {re:mixin}
	at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?] {re:mixin}
	at java.io.FileInputStream.<init>(FileInputStream.java:111) ~[?:?] {re:mixin}
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86) ~[?:?] {}
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:189) ~[?:?] {}
	at java.net.URL.openStream(URL.java:1161) ~[?:?] {re:mixin}
	at gg.essential.util.HelpersKt.findCodeSource(helpers.kt:175) ~[Essential%20(forge_1.20.1).jar%231721!/:?] {re:mixin,re:classloading}
	at gg.essential.util.HelpersKt.addEssentialResourcePack(helpers.kt:205) ~[Essential%20(forge_1.20.1).jar%231721!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.packs.repository.PackRepository.handler$cee000$addEssentialResourcePack(PackRepository.java:540) ~[client-1.20.1-20230612.114412-srg.jar%231002!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:resources.MixinResourcePackList from mod

**Comment by Random-Scientist** [comment]
I am 99% certain that your issue is with the [Essential](https://essential.gg/en) mod, which is not the mod this issue tracker is for. Feel free to reopen this issue if you are certain that the mod causing issues is the [Essentials](https://www.curseforge.com/minecraft/mc-mods/essentials) vanilla+/automation mod.
