### ISSUE TITLE
Circuit Crash

### ISSUE THREAD

**Issue by StrangerSon712** [Da-Technomancer/Essentials#46]
**Describe the bug**
I right clicked on a circuit and it crashed and wouldn't load the world that I right clicked the circuit in.

**Additional context [Optional]**
Modlist:
Alex's mobs
AppleSkin
AutoRegLib
Citadel
Controlling
Crossroads
Curios
Essentials
Geckolib beta
Ice and Fire
JEI
Mana and artifice
mgui
MouseTweaks
Patchouli
Ratlantis
Rats
Tetra
The One Probe
Corail Tombstone
Xaero's Minimap
Xaero's World map

Crash Report

// I blame Dinnerbone.

Time: 12/12/20 12:06 PM
Description: Rendering screen

java.lang.OutOfMemoryError: Java heap space
	at net.minecraftforge.fml.hooks.BasicEventHooks.onRenderTickStart(BasicEventHooks.java:75) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:974) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_238195_a_(Minecraft.java:1771) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$loadWorld$29(Minecraft.java:1799) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$7911/1839532943.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.Minecraft.lambda$deleteWorld$30(Minecraft.java:1829) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$7912/1057089480.proceed(Unknown Source) ~[?:?] {}
	at com.github.alexthe666.rats.client.event.ClientEvents.onOpenGui(ClientEvents.java:106) ~[?:7.0.1-1.16.3] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_110_ClientEvents_onOpenGui_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:291) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:491) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.10.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$482/1700078557.call(Unknown Source) [forge-1.16.4-35.1.10.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.fml.hooks.BasicEventHooks.onRenderTickStart(BasicEventHooks.java:75) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:974) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_238195_a_(Minecraft.java:1771) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$loadWorld$29(Minecraft.java:1799) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$7911/1839532943.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.Minecraft.lambda$deleteWorld$30(Minecraft.java:1829) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$7912/1057089480.proceed(Unknown Source) ~[?:?] {}
	at com.github.alexthe666.rats.client.event.ClientEvents.onOpenGui(ClientEvents.java:106) ~[?:7.0.1-1.16.3] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_110_ClientEvents_onOpenGui_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:291) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:491) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.screen.WorldLoadProgressScreen
	Mouse location: Scaled: (-112, 138). Absolute: (-371.566406, 319.015625)
	Screen size: Scaled: (427, 240). Absolute: (1708, 960). Scale factor of 4.000000
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:494) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4-forge-35.1.10.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.10.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Mac OS X (x86_64) version 10.14.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1874750704 bytes (1787 MB) / 2684354560 bytes (2560 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.10.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.10.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.10.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.10.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.10.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.10
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.10-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		tombstone-6.0.2.jar                               |Corail Tombstone              |tombstone                     |6.0.2               |DONE      |NOSIGNATURE
		theoneprobe-1.16-3.0.4-beta.jar                   |The One Probe                 |theoneprobe                   |1.16-3.0.4-beta     |DONE      |NOSIGNATURE
		MouseTweaks-2.13-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.13                |DONE      |NOSIGNATURE
		mana-and-artifice-1.1.0.4.jar                     |Mana and Artifice             |mana-and-artifice             |1.1.0.4             |DONE      |NOSIGNATURE
		jei-1.16.3-7.6.0.51.jar                           |Just Enough Items             |jei                           |7.6.0.50            |DONE      |NOSIGNATURE
		crossroads-1.16.4-2.5.2.jar                       |Crossroads                    |crossroads                    |version             |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.10-universal.jar                |Forge                         |forge                         |35.1.10             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		curios-forge-1.16.4-4.0.2.1.jar                   |Curios API                    |curios                        |1.16.4-4.0.2.1      |DONE      |NOSIGNATURE
		tetra-1.16.4-3.3.1.jar                            |Tetra                         |tetra                         |3.3.1               |DONE      |NOSIGNATURE
		Patchouli-1.16.2-47.jar                           |Patchouli                     |patchouli                     |1.16.2-47           |DONE      |NOSIGNATURE
		essentials-1.16.4-2.9.5.jar                       |Essentials                    |essentials                    |1.16.4-2.9.5        |DONE      |NOSIGNATURE
		Xaeros_Minimap_20.28.1_Forge_1.16.4.jar           |Xaero's Minimap               |xaerominimap                  |20.28.1             |DONE      |NOSIGNATURE
		forge-1.16.4-geckolib-3.0.0-beta.10.jar           |GeckoLib                      |geckolib3                     |3.0.0-beta.10       |DONE      |NOSIGNATURE
		XaerosWorldMap_1.11.3_Forge_1.16.4.jar            |Xaero's World Map             |xaeroworldmap                 |1.11.3              |DONE      |NOSIGNATURE
		mgui-1.16.4-3.1.3.jar                             |mgui                          |mgui                          |3.1.3               |DONE      |NOSIGNATURE
		Controlling-7.0.0.9.jar                           |Controlling                   |controlling                   |7.0.0.9             |DONE      |NOSIGNATURE
		citadel-1.5.3.jar                                 |Citadel                       |citadel                       |1.5.3               |DONE      |NOSIGNATURE
		alexsmobs-1.0.1.jar                               |Alex's Mobs                   |alexsmobs                     |1.0.1               |DONE      |NOSIGNATURE
		iceandfire-2.1.3-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.3-1.16.4        |DONE      |NOSIGNATURE
		rats-7.0.1-1.16.3.jar                             |Rats                          |rats                          |7.0.1               |DONE      |NOSIGNATURE
		ratlantis-1.0.0-1.16.3.jar                        |Rats: Ratlantis               |ratlantis                     |1.0.0-1.16.3        |DONE      |NOSIGNATURE
		AutoRegLib-1.6-46.jar                             |AutoRegLib                    |autoreglib                    |1.6-46              |DONE      |NOSIGNATURE
	Crash Report UUID: 7602dd2c-0f4b-4429-a52c-d698dd70c24a
	Patchouli open book context: n/a
	Launched Version: 1.16.4-forge-35.1.10
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: NVIDIA GeForce GT 650M OpenGL Engine GL version 2.1 NVIDIA-12.0.24 355.11.10.50.10.103, NVIDIA Corporation
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	GPU Warnings: version: 2.1
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz

**Comment by Da-Technomancer** [comment]
Where you using a Delay Circuit, by any chance?
You're using Essentials 1.16.4-2.9.5. The current Essentials version (1.16.4-2.9.6) fixes a bug similar to what you're describing involving Delay Circuits. 

Update to the latest Essentials, and re-open this issue if the problem persists.

**Comment by StrangerSon712** [comment]
I updated, and I think I was using delay circuits. However, the problem has persisted.

**Comment by StrangerSon712** [comment]
---- Minecraft Crash Report ----
// My bad.

Time: 12/13/20 1:48 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at com.Da_Technomancer.crossroads.API.effects.EnergizeEffect.getHitHandler(EnergizeEffect.java:66) ~[?:1.16.4-2.5.2] {re:classloading}
	at com.Da_Technomancer.crossroads.API.effects.EnergizeEffect.doBeamEffect(EnergizeEffect.java:24) ~[?:1.16.4-2.5.2] {re:classloading}
	at com.Da_Technomancer.crossroads.API.beams.BeamManager.emit(BeamManager.java:50) ~[?:1.16.4-2.5.2] {re:classloading}
	at com.Da_Technomancer.crossroads.tileentities.beams.BeamReflectorTileEntity.doEmit(BeamReflectorTileEntity.java:44) ~[?:1.16.4-2.5.2] {re:classloading}
	at com.Da_Technomancer.crossroads.API.templates.BeamRenderTE.func_73660_a(BeamRenderTE.java:121) ~[?:1.16.4-2.5.2] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.Da_Technomancer.crossroads.API.effects.EnergizeEffect.getHitHandler(EnergizeEffect.java:66) ~[?:1.16.4-2.5.2] {re:classloading}
	at com.Da_Technomancer.crossroads.API.effects.EnergizeEffect.doBeamEffect(EnergizeEffect.java:24) ~[?:1.16.4-2.5.2] {re:classloading}
	at com.Da_Technomancer.crossroads.API.beams.BeamManager.emit(BeamManager.java:50) ~[?:1.16.4-2.5.2] {re:classloading}
	at com.Da_Technomancer.crossroads.tileentities.beams.BeamReflectorTileEntity.doEmit(BeamReflectorTileEntity.java:44) ~[?:1.16.4-2.5.2] {re:classloading}
	at com.Da_Technomancer.crossroads.API.templates.BeamRenderTE.func_73660_a(BeamRenderTE.java:121) ~[?:1.16.4-2.5.2] {re:classloading}
-- Block entity being ticked --
Details:
	Name: crossroads:beam_reflector // com.Da_Technomancer.crossroads.tileentities.beams.BeamReflectorTileEntity
	Block: Block{crossroads:beam_reflector}[facing=west]
	Block location: World: (-15,56,-108), Chunk: (at 1,3,4 in -1,-7; contains blocks -16,0,-112 to -1,255,-97), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Block: Block{crossroads:beam_reflector}[facing=west]
	Block location: World: (-15,56,-108), Chunk: (at 1,3,4 in -1,-7; contains blocks -16,0,-112 to -1,255,-97), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:classloading,pl:accesstransformer:B}


-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 2025
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,55,8), Chunk: (at 8,3,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 720808 game time, 8192 day time
	Level name: Test
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 11054 (now: true), thunder time: 16054 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74] {}


-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Mac OS X (x86_64) version 10.14.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1422459736 bytes (1356 MB) / 3053453312 bytes (2912 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.10.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.10.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.10.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.10.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.10.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.10
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.10-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		tombstone-6.0.2.jar                               |Corail Tombstone              |tombstone                     |6.0.2               |DONE      |NOSIGNATURE
		theoneprobe-1.16-3.0.4-beta.jar                   |The One Probe                 |theoneprobe                   |1.16-3.0.4-beta     |DONE      |NOSIGNATURE
		MouseTweaks-2.13-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.13                |DONE      |NOSIGNATURE
		mana-and-artifice-1.1.0.4.jar                     |Mana and Artifice             |mana-and-artifice             |1.1.0.4             |DONE      |NOSIGNATURE
		jei-1.16.3-7.6.0.51.jar                           |Just Enough Items             |jei                           |7.6.0.50            |DONE      |NOSIGNATURE
		crossroads-1.16.4-2.5.2.jar                       |Crossroads                    |crossroads                    |version             |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.10-universal.jar                |Forge                         |forge                         |35.1.10             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		curios-forge-1.16.4-4.0.2.1.jar                   |Curios API                    |curios                        |1.16.4-4.0.2.1      |DONE      |NOSIGNATURE
		tetra-1.16.4-3.3.1.jar                            |Tetra                         |tetra                         |3.3.1               |DONE      |NOSIGNATURE
		Patchouli-1.16.2-47.jar                           |Patchouli                     |patchouli                     |1.16.2-47           |DONE      |NOSIGNATURE
		essentials-1.16.4-2.9.6.jar                       |Essentials                    |essentials                    |1.16.4-2.9.6        |DONE      |NOSIGNATURE
		Xaeros_Minimap_20.28.1_Forge_1.16.4.jar           |Xaero's Minimap               |xaerominimap                  |20.28.1             |DONE      |NOSIGNATURE
		forge-1.16.4-geckolib-3.0.0-beta.10.jar           |GeckoLib                      |geckolib3                     |3.0.0-beta.10       |DONE      |NOSIGNATURE
		XaerosWorldMap_1.11.3_Forge_1.16.4.jar            |Xaero's World Map             |xaeroworldmap                 |1.11.3              |DONE      |NOSIGNATURE
		mgui-1.16.4-3.1.3.jar                             |mgui                          |mgui                          |3.1.3               |DONE      |NOSIGNATURE
		Controlling-7.0.0.9.jar                           |Controlling                   |controlling                   |7.0.0.9             |DONE      |NOSIGNATURE
		citadel-1.5.3.jar                                 |Citadel                       |citadel                       |1.5.3               |DONE      |NOSIGNATURE
		alexsmobs-1.0.1.jar                               |Alex's Mobs                   |alexsmobs                     |1.0.1               |DONE      |NOSIGNATURE
		iceandfire-2.1.3-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.3-1.16.4        |DONE      |NOSIGNATURE
		rats-7.0.1-1.16.3.jar                             |Rats                          |rats                          |7.0.1               |DONE      |NOSIGNATURE
		ratlantis-1.0.0-1.16.3.jar                        |Rats: Ratlantis               |ratlantis                     |1.0.0-1.16.3        |DONE      |NOSIGNATURE
		AutoRegLib-1.6-46.jar                             |AutoRegLib                    |autoreglib                    |1.6-46              |DONE      |NOSIGNATURE
	Crash Report UUID: 8fa156e7-ae95-4b9c-a3fa-8141637b7342
	Patchouli open book context: n/a
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:tombstone (incompatible), mod:theoneprobe, mod:mousetweaks, mod:crossroads, mod:forge, mod:patchouli (incompatible), mod:essentials (incompatible), mod:appleskin, mod:controlling (incompatible), mod:autoreglib (incompatible), mod:jei, mod:tetra, mod:mgui (incompatible), mod:mana-and-artifice, mod:curios, mod:xaerominimap, mod:geckolib3 (incompatible), mod:xaeroworldmap, mod:citadel (incompatible), mod:alexsmobs, mod:iceandfire (incompatible), mod:rats, mod:ratlantis
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by Da-Technomancer** [comment]
Attached is a special version of Crossroads which will allow you to launch and play the world (you have to take the .jar out of the zip file). It is a workaround for the crash- it does not fix the underlying bug. 

In this world, you have a Beam Reflector at coordinates [-15,56,-108], which is facing west. 
Once you get the world working, could you find that beam reflector and tell me what it is pointing at? Specifically what type of block it is pointed towards? That would allow me to fix the underlying issue more easily. 
[crossroads-1.16.4-2.5.2.jar.zip](https://github.com/Da-Technomancer/Essentials/files/5689490/crossroads-1.16.4-2.5.2.jar.zip)

**Comment by StrangerSon712** [comment]
![2020-12-15_13 24 49](https://user-images.githubusercontent.com/64751093/102262595-f3425200-3ed8-11eb-8ec1-a91016e3786e.png)

**Comment by StrangerSon712** [comment]
Note targeted block position

**Comment by StrangerSon712** [comment]
Everything Crossroads is gone now?

**Comment by StrangerSon712** [comment]
And.. It was my fault. I didn't take the jar out.

**Comment by StrangerSon712** [comment]
It's back but everything is the wrong rotation. I think it was facing a gold drill, but I'm not certain.

**Comment by StrangerSon712** [comment]
![2020-12-15_13 57 27](https://user-images.githubusercontent.com/64751093/102266026-867d8680-3edd-11eb-8ab9-5c15c0438f39.png)
I was retrofitting my beams for a mob farm. It was definitely the gold drill. Also gears disappear and large gears are ghost blocks?

**Comment by Da-Technomancer** [comment]
Opening a world with a mod missing can have a wide variety of side effects. Sounds like you accidentally opened your world without Crossroads properly installed, which make various gears disappear/become ghost blocks. If you have a backup of the world, I'd suggest reverting to it.
